apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: inference-consumer
        image: 192.168.5.56:5000/inference-consumer:latest
        imagePullPolicy: Always
        env:
         - name: KAFKA_BROKER
           value: "kafka-service:9092"
         - name: ML_SERVER
           value: "http://ml-server:5000/infer"  # Use the correct service name
         - name: MONGO_URI
           value: "mongodb://mongodb-service:27017/"


      - name: db-consumer
        image: 192.168.5.56:5000/db-consumer:latest
        imagePullPolicy: Always
      restartPolicy: Never
