apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-server
  template:
    metadata:
      labels:
        app: ml-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ml-server
        image: 192.168.5.56:5000/ml-server:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
